### ISSUE TITLE
NXP seems to like naming bitfields "RESERVED"

### ISSUE THREAD

**Issue by porkybrain** [posborne/cmsis-svd#11]
here https://github.com/posborne/cmsis-svd/blob/9f2ca607848e5b368f89e0888a0e13c7b43cf764/data/NXP/LPC15xx_v0.7.svd for example there are many registers which contain a bitfields named RESERVED. These need to be discared (especially if two RESERVED fields occure in one register) somewhere in the chain of processing. Where would it be best to do it? 

In my opinion its NXP's error so they should fix it but thats probably not going to happen so should we filter them out while parsing or should I do it in my Kvasir specific parser?

**Comment by kblomqvist** [comment]
I think they use these for padding... to align structure members to their "natural" address boundaries in C.

For example:

```
typedef struct {                             
  __IO uint8_t   B[76];                      
  __I  uint32_t  RESERVED0[45];
  __IO uint32_t  W[76];                      
  __I  uint32_t  RESERVED1[1908];
  __IO uint32_t  DIR[3];                     
  __I  uint32_t  RESERVED2[29];
  __IO uint32_t  MASK[3];                    
  __I  uint32_t  RESERVED3[29];
  __IO uint32_t  PIN[3];                     
  __I  uint32_t  RESERVED4[29];
  __IO uint32_t  MPIN[3];                    
  __I  uint32_t  RESERVED5[29];
  __IO uint32_t  SET[3];                     
  __I  uint32_t  RESERVED6[29];
  __O  uint32_t  CLR[3];                     
  __I  uint32_t  RESERVED7[29];
  __O  uint32_t  NOT[3];                     
} LPC_GPIO_PORT_Type;
```

**Comment by porkybrain** [comment]
there seem to be multiple cases, @kblomqvist you case is where whole registers are named reserved. I guess the RESERVED bitfields could be usefull when generating unions or something but only if NXPs parser sucks ;)

**Comment by 0xc0170** [comment]
@kblomqvist is right with padding. It's common , I have seen in various cmsis vendors header files.

What's NXP error?

**Comment by porkybrain** [comment]
<register>
			<dim>18</dim>
			<dimIncrement>0x10</dimIncrement>
			<dimIndex>0-17</dimIndex>
			<name>CFG%s</name>
			<description>Configuration register for DMA channel 0.</description>
			<addressOffset>0x400</addressOffset>
			<access>read-write</access>
			<resetValue>0</resetValue>
			<resetMask>0x00000000</resetMask>
			<fields>
				<field>
					<name>PERIPHREQEN</name>
					<description>Peripheral request Enable. If a DMA channel is used to perform a memory-to-memory move, any peripheral DMA request associated with that channel can be disabled to prevent any interaction between the peripheral and the DMA controller.</description>
					<bitRange>[0:0]</bitRange>
					<enumeratedValues>
					<name>ENUM</name>
						<enumeratedValue>
							<name>DISABLED</name>
							<description>Disabled. Peripheral DMA requests are disabled.</description>
							<value>0</value>
						</enumeratedValue>
						<enumeratedValue>
							<name>ENABLED</name>
							<description>Enabled. Peripheral DMA requests are enabled.</description>
							<value>1</value>
						</enumeratedValue>
					</enumeratedValues>
				</field>
				<field>
					<name>HWTRIGEN</name>
					<description>Hardware Triggering Enable for this channel.</description>
					<bitRange>[1:1]</bitRange>
					<enumeratedValues>
					<name>ENUM</name>
						<enumeratedValue>
							<name>DISABLED</name>
							<description>Disabled. Hardware triggering is not used.</description>
							<value>0</value>
						</enumeratedValue>
						<enumeratedValue>
							<name>ENABLED</name>
							<description>Enabled. Use hardware triggering.</description>
							<value>1</value>
						</enumeratedValue>
					</enumeratedValues>
				</field>
				<field>
					<name>RESERVED</name>
					<description>Reserved. Read value is undefined, only zero should be written.</description>
					<bitRange>[3:2]</bitRange>

				</field>
				<field>
					<name>TRIGPOL</name>
					<description>Trigger Polarity. Selects the polarity of a hardware trigger for this channel.</description>
					<bitRange>[4:4]</bitRange>
					<enumeratedValues>
					<name>ENUM</name>
						<enumeratedValue>
							<name>ACTIVE_LOW__FALLING</name>
							<description>Active low - falling edge. Hardware trigger is active low or falling edge triggered, based on TRIGTYPE.</description>
							<value>0</value>
						</enumeratedValue>
						<enumeratedValue>
							<name>ACTIVE_HIGH__RISING</name>
							<description>Active high - rising edge. Hardware trigger is active high or rising edge triggered, based on TRIGTYPE.</description>
							<value>1</value>
						</enumeratedValue>
					</enumeratedValues>
				</field>
				<field>
					<name>TRIGTYPE</name>
					<description>Trigger Type. Selects hardware trigger as edge triggered or level triggered.</description>
					<bitRange>[5:5]</bitRange>
					<enumeratedValues>
					<name>ENUM</name>
						<enumeratedValue>
							<name>EDGE</name>
							<description>Edge. Hardware trigger is edge triggered.</description>
							<value>0</value>
						</enumeratedValue>
						<enumeratedValue>
							<name>LEVEL</name>
							<description>Level. Hardware trigger is level triggered. Note that when level triggering without burst (BURSTPOWER = 0) is selected, only hardware triggers should be used on that channel.</description>
							<value>1</value>
						</enumeratedValue>
					</enumeratedValues>
				</field>
				<field>
					<name>TRIGBURST</name>
					<description>Trigger Burst. Selects whether hardware triggers cause a single or burst transfer.</description>
					<bitRange>[6:6]</bitRange>
					<enumeratedValues>
					<name>ENUM</name>
						<enumeratedValue>
							<name>SINGLE_TRANSFER</name>
							<description>Single transfer. Hardware trigger causes a single transfer.</description>
							<value>0</value>
						</enumeratedValue>
						<enumeratedValue>
							<name>BURST_TRANSFER</name>
							<description>Burst transfer. When the trigger for this channel is set to edge triggered, a hardware trigger causes a burst transfer, as defined by BURSTPOWER. When the trigger for this channel is set to level triggered, a hardware trigger causes transfers to continue as long as the trigger is asserted, unless the transfer is complete.</description>
							<value>1</value>
						</enumeratedValue>
					</enumeratedValues>
				</field>
				<field>
					<name>RESERVED</name>
					<description>Reserved. Read value is undefined, only zero should be written.</description>
					<bitRange>[7:7]</bitRange>

				</field>
				<field>
					<name>BURSTPOWER</name>
					<description>Burst Power is used in two ways. It always selects the address wrap size when SrcBurstWrap and/or DstBurstWrap is modes are selected (see descriptions elsewhere in this register). When the TRIGBURST field elsewhere in this register = 1, Burst Power selects how many transfers are performed for each DMA trigger. This can be used, for example, with peripherals that contain a FIFO that can initiate a DMA operation when the FIFO reaches a certain level. 0000: Burst size = 1 (20). 0001: Burst size = 2 (21). 0010: Burst size = 4 (22). ... 1010: Burst size = 1024 (210). This corresponds to the maximum supported transfer count. others: not supported.</description>
					<bitRange>[11:8]</bitRange>

				</field>
				<field>
					<name>RESERVED</name>
					<description>Reserved. Read value is undefined, only zero should be written.</description>
					<bitRange>[13:12]</bitRange>

				</field>
				<field>
					<name>SRCBURSTWRAP</name>
					<description>Source Burst Wrap. When enabled, the source data address for the DMA is wrapped, meaning that the source address range for each burst will be the same. As an example, this could be used to read several sequential registers from a peripheral for each DMA burst, reading the same registers again for each burst.</description>
					<bitRange>[14:14]</bitRange>
					<enumeratedValues>
					<name>ENUM</name>
						<enumeratedValue>
							<name>DISABLED</name>
							<description>Disabled. Source burst wrapping is not enabled for this DMA channel.</description>
							<value>0</value>
						</enumeratedValue>
						<enumeratedValue>
							<name>ENABLED</name>
							<description>Enabled. Source burst wrapping is enabled for this DMA channel.</description>
							<value>1</value>
						</enumeratedValue>
					</enumeratedValues>
				</field>
				<field>
					<name>DSTBURSTWRAP</name>
					<description>Destination Burst Wrap. When enabled, the destination data address for the DMA is wrapped, meaning that the destination address range for each burst will be the same. As an example, this could be used to write several sequential registers to a peripheral for each DMA burst, writing the same registers again for each burst.</description>
					<bitRange>[15:15]</bitRange>
					<enumeratedValues>
					<name>ENUM</name>
						<enumeratedValue>
							<name>DISABLED</name>
							<description>Disabled. Destination burst wrapping is not enabled for this DMA channel.</description>
							<value>0</value>
						</enumeratedValue>
						<enumeratedValue>
							<name>ENABLED</name>
							<description>Enabled. Destination burst wrapping is enabled for this DMA channel.</description>
							<value>1</value>
						</enumeratedValue>
					</enumeratedValues>
				</field>
				<field>
					<name>CHPRIORITY</name>
					<description>Priority of this channel when multiple DMA requests are pending. This description reflects a 3-bit priority field giving 8 priority levels. A specific instance of the SDMA might have anywhere from 2 to 16 priority levels (1 to 4 bits for the CH_PRIORITY field). 0x0 = highest priority. 0x7 = lowest priority.</description>
					<bitRange>[18:16]</bitRange>

				</field>
				<field>
					<name>RESERVED</name>
					<description>Reserved. Read value is undefined, only zero should be written.</description>
					<bitRange>[31:19]</bitRange>
					
				</field>
			</fields>
		</register>

there are 4 fields in this register all named RESERVED. They can't be using them for padding because they are all named the exact same thing. Besides an intelligent parser could easily figure out where the reserved bits are without explicitly defined ranges.

**Comment by porkybrain** [comment]
After blowing off steam about NXPs design decisions it time to take the pragmatic approach ;) I implemented a free function `remove_reserved` which should solve this issue.
