### ISSUE TITLE
remove_reserved does the opposite of what it says

### ISSUE THREAD

**Issue by martinhansdk** [posborne/cmsis-svd#113]
In the call to `SVDParser.for_packaged_svd()`, `remove_reserved=False` causes reserved register fields to be removed and `remove_reserved=True` causes them to be kept. From the naming, I would have expected the opposite behavior.

I believe, the following code in `_parse_registers()` is to blame:
```
if self.remove_reserved or 'reserved' not in node.name.lower():
    fields.append(node)
```

This should probably be:
```
if not self.remove_reserved or 'reserved' not in node.name.lower():
    fields.append(node)
```

**Comment by posborne** [comment]
I think I agree @martinhansdk, could you open a PR with this change?
