### ISSUE TITLE
can you make a version 1.1 so pip install is easier?

### ISSUE THREAD

**Issue by porkybrain** [posborne/cmsis-svd#22]
this repo has changed a lot since version one, some people interested in developing Kvasir have been complaining that installing this dependency is too complicated (pip installing from a git hub repo took me a bit of time to figure out myself). Could we make a version 1.1?

**Comment by posborne** [comment]
Sure.  I'm traveling so it will probably be a few days.

**Comment by porkybrain** [comment]
No problem, have fun!

**Comment by posborne** [comment]
Sorry for the delay.  Version 0.2 is now published: https://pypi.python.org/pypi/cmsis-svd/0.2
