### ISSUE TITLE
Some of the STMicro SVDs are named .svd

### ISSUE THREAD

**Issue by porkybrain** [posborne/cmsis-svd#6]
https://github.com/posborne/cmsis-svd/tree/master/data/STMicro some of the STMicro SVDs are named .svd, all other files are names *.xml, is there a reason for the .svd ending rather than xml or should I change them all?

**Comment by kblomqvist** [comment]
`.svd` is an extension what ARM use.

See for example, http://www.keil.com/pack/doc/CMSIS/SVD/html/svd__example_pg.html
`<!-- File naming: <part/series name>.svd -->`

Additionally all SVD files provided via CMSIS-SVD download page are `.svd`:
http://www.keil.com/pack/doc/CMSIS/SVD/html/svd_web_public_pg.html

**Comment by porkybrain** [comment]
Ok so they are really interchangeable. Any reason not to just rename them into xml? For uniformity sake.

**Comment by kblomqvist** [comment]
For uniformity sake you can choose `.xml` if you like. I would go with the file extension specified by ARM.

**Comment by posborne** [comment]
For now, I think renaming to .XML for consistency makes sense.  I'm guessing there is no strong preference from ARM either.  CC @salkinium @0xc0170.

**Comment by 0xc0170** [comment]
Agree with consistency @posborne .

I would go with .svd as pointed out earlier. However we can see most of the files in this repo are xml. I'll try to find out more, will add any update here.

**Comment by porkybrain** [comment]
If they are all officially .svd maybe we should rename all the other ones. 

----- Ursprüngliche Nachricht -----
Von: "Martin Kojtal" <notifications@github.com>
Gesendet: ‎15.‎09.‎2015 16:28
An: "posborne/cmsis-svd" <cmsis-svd@noreply.github.com>
Cc: "Odin Holmes" <holmes.odin@gmail.com>
Betreff: Re: [cmsis-svd] Some of the STMicro SVDs are named .svd (#6)

Agree with consistency @posborne .
I would go with .svd as pointed out earlier. However we can see most of the files in this repo are xml. I'll try to find out more, will add any update here.

**Comment by posborne** [comment]
I'm amenable to that suggestion.  I can reopen, adjust the tests, and rename later tonight.

**Comment by porkybrain** [comment]
I am for  .svd, all the files I found  were originally  .svd too, that seems to be what everyone else is naming them. 

----- Ursprüngliche Nachricht -----
Von: "Paul Osborne" <notifications@github.com>
Gesendet: ‎15.‎09.‎2015 23:55
An: "posborne/cmsis-svd" <cmsis-svd@noreply.github.com>
Cc: "Odin Holmes" <holmes.odin@gmail.com>
Betreff: Re: [cmsis-svd] Some of the STMicro SVDs are named .svd (#6)

I'm amenable to that suggestion. I can reopen, adjust the tests, and rename later tonight.

**Comment by posborne** [comment]
We are now 100% .svd
