### ISSUE TITLE
CC26X0 svd file request

### ISSUE THREAD

**Issue by luojia65** [posborne/cmsis-svd#69]
CC26X0 (as well as CC26X0R2F) is a series of Cortex-M3 MCU with built-in RF support. It is a new series though, it would be very useful if there is a SVD file here in this project. 
(As far as I know, TI does not offer this kind of file officially, but maybe we can convert from device database from TI's IDEs.)

**Comment by deadprogram** [comment]
Hello @luojia65 there is this tool https://github.com/m-labs/dslite2svd is we run the code in this fork https://github.com/wezm/dslite2svd we should be able to generate the SVD file.

**Comment by luojia65** [comment]
Wow thanks, I'd check it out @deadprogram
